all:
    hosts:
    children:
        mongodb:
            hosts:
                mongo-master.vinga.tk:
                    host_name: mongo-master
                    host_ip: "15.207.46.69"
                    host_private_ip: "172.31.30.122"
                    cron_renew_day: "1"
                mongo-slave1.vinga.tk:
                    host_name: mongo-slave1
                    host_ip: "15.207.68.126"
                    host_private_ip: "172.31.29.198"
                    cron_renew_day: "2"
                mongo-slave2.vinga.tk:
                    host_name: mongo-slave2
                    host_ip: "3.7.119.75"
                    host_private_ip: "172.31.20.21"
                    cron_renew_day: "3"
                mongo-arbiter.vinga.tk:
                    host_name: mongo-arbiter
                    host_ip: "52.66.172.180"
                    host_private_ip: "172.31.17.125"
                    cron_renew_day: "4"
                mongo-delayed.vinga.tk:
                    host_name: mongo-delayed
                    host_ip: "3.7.26.176"
                    host_private_ip: "172.31.26.68"
                    cron_renew_day: "5"                    
        primary:
            hosts:
                mongo-master.vinga.tk:
        secondaries:
            hosts:
                mongo-slave1.vinga.tk:
                    priority: 1
                mongo-slave2.vinga.tk:
                    priority: 1
                mongo-delayed.vinga.tk:
                    priority: 0
        arbiter:
            hosts:
                mongo-arbiter.vinga.tk:
        delayed:
            hosts:
               mongo-delayed.vinga.tk:
        monitoring_server:
            hosts:
                mongo-arbiter.vinga.tk:
        monitoring_clients:
            hosts:
                mongo-master.vinga.tk:
                mongo-slave1.vinga.tk:
                mongo-slave2.vinga.tk:
                mongo-delayed.vinga.tk:
        backup_server:
            hosts:
                mongo-arbiter.vinga.tk:
    vars:
        remote_user: ubuntu
        ansible_ssh_private_key_file: ~/.ssh/id_rsa
        delay: "300"
        cluster_size: 3
        host_key_checking: "False"
        mongodb_version: "4.2"
        mongodb_replicaset_name: rs0
        mongodb_db_path: "/mnt/mongo_data"
        mongodb_user_user_admin_any_database_name: siteUserAdmin
        mongodb_user_user_admin_any_database_password: "strong-pwd-1"
        mongodb_user_root_name: siteRootAdmin
        mongodb_user_root_password: "strong-pwd-2"
        mongodb_main_database: siteMainDataBase
        mongodb_user_readwrite_main_database_name: "siteDataBaseUser"
        mongodb_user_readwrite_main_database_password: "strong-pwd-3"
        partitioning_device_name: "/dev/nvme0n1"
        partitioning_partition_name: "/dev/nvme0n1p1"
        partitioning_luks_passphrase: "strong-pwd-4"
        partitioning_luks_name: cryptolvm
        partitioning_vg_name: mongo_vg
        partitioning_lv_name: mongo_data
        certbot_admin_email: vishalonwork@gmail.com
        monitoring_password: "strong-pwd-5"
        monitoring_db_user_name: "pmm"
        monitoring_db_user_password: "strong-pwd-5"
        backup_db_user_name: backup
        backup_db_user_password: "strong-pwd-6"
        backup_region: "ap-southeast-1"
        backup_bucket: "my-project-mongodb-backup"
        backup_secret: "aws-secret"
        backup_public: "aws-public"
        backup_minute: "30"
        backup_hour: "1"
        
