- name: Check file /dev/mapper/{{ partitioning_vg_name }}-{{ partitioning_lv_name }} exists
  stat:
    path: "/dev/mapper/{{ partitioning_vg_name }}-{{ partitioning_lv_name }}"
  register: file_details

- name: Install cryptsetup for encryption at rest
  apt:
    name: cryptsetup-bin
    update_cache: yes
  when: file_details.stat.exists == false

- name: Create /etc/luks directory if it does not exist
  file:
    path: /etc/luks
    state: directory
    owner: root
    mode: "700"
  when: file_details.stat.exists == false

- name: Create luks kefile for encryption
  template:
    src: luks_keyfile.j2
    dest: /etc/luks/keyfile
    owner: root
    mode: "700"
  when: file_details.stat.exists == false

- name: Create a new primary partition
  parted:
    device: "{{ partitioning_device_name }}"
    number: 1
    state: present
  when: file_details.stat.exists == false
  
- name: create LUKS container (remains unchanged if it already exists)
  luks_device:
    device: "{{ partitioning_partition_name }}"
    state: "opened"
    keyfile: "/etc/luks/keyfile"
    name: "{{ partitioning_luks_name }}"
  when: file_details.stat.exists == false

- name: Create a volume group on top of /dev/mapper/{{partitioning_luks_name}}
  lvg:
    vg: "{{ partitioning_vg_name }}"
    pvs: "/dev/mapper/{{partitioning_luks_name}}"
  when: file_details.stat.exists == false

- name: Create a logical volume of 90% the size
  lvol:
    vg: "{{ partitioning_vg_name }}"
    lv: "{{ partitioning_lv_name }}"
    size: 90%FREE
  when: file_details.stat.exists == false

- name: Create a filesystem on volume
  filesystem:
    fstype: xfs
    dev: "/dev/mapper/{{ partitioning_vg_name }}-{{ partitioning_lv_name }}"
  when: file_details.stat.exists == false
  
- name: Mount DB directory
  mount:
    path: "{{ mongodb_db_path }}"
    src: "/dev/mapper/{{ partitioning_vg_name }}-{{ partitioning_lv_name }}"
    state: mounted
    fstype: xfs
  when: file_details.stat.exists == false