{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    {{- include "tekion-app.labels" . | nindent 4 }}
data:
{{- range $key, $val := .Values.secret }}
{{ printf "%s: %s" ($key | quote) ($val | quote) | indent 2 }}
{{- end }}
{{- end }}
