{{- if .Values.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secret
  labels:
    {{- include "tekion-app.labels" . | nindent 4 }}
data:
{{- $chartName := .Chart.Name}}
{{- range splitList "\n" (.Files.Get "secrets.yaml.dec") }}
{{- if not (. | trim | empty) }}
{{- $kv := . | splitn ": " 2 }}
{{ printf "%s: %s" ($kv._0 | quote) ((b64enc ($kv._1)) | quote) | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
