apiVersion: v1
kind: Service
metadata:
  name: {{ include "tekion-app.fullname" . }}
  labels:
    {{- include "tekion-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
{{- if .Values.extraPorts }}
{{ toYaml .Values.extraPorts | trim | indent 4 }}
{{- end }}
  selector:
    {{- include "tekion-app.selectorLabels" . | nindent 4 }}
