affinity: {}
autoscaling:
  enabled: false
  maxReplicas: 100
  minReplicas: 1
  targetCPUUtilizationPercentage: 80
extraPorts:
- name: metrics
  port: 9012
  targetPort: 9012
fullnameOverride: ''
image:
  pullPolicy: IfNotPresent
  repository: vinga2805/tekion
  tag: snapshot_0.0.1_master_59dafae
imagePullSecrets: []
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
  enabled: false
  hosts:
  - host: tekion.vinga.tk
    paths:
    - /
  tls: []
nameOverride: ''
nodeSelector: {}
podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: '9012'
  prometheus.io/scrape: 'true'
podSecurityContext: {}
replicaCount: 1
resources: {}
securityContext: {}
service:
  port: 80
  targetPort: 8080
  type: ClusterIP
serviceAccount:
  annotations: {}
  create: true
  name: ''
tolerations: []
volumeMounts:
- mountPath: /var/log/apps/teslaDyDB
  name: log-storage
